config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "home#index"
  get 'home/index'

  resources :activity_types
  resources :activities
  
  get 'about', to: "about_contact#about"
  get 'contact', to: "about_contact#contact"
end

app/views/shared/_head.html.erb
<head>
  <title>MoveAndGrove</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%# <link href="https://fonts.googleapis.com/css?family=Titillium+Web:300,400&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet"> %>
  <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'form_vue' %>

  <script src="https://code.iconify.design/1/1.0.3/iconify.min.js"></script>
</head>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <img src="/images/logo-part-sm.png" class="d-inline-block align-top">
      <span>Move And Grove</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="Navbar">
      <ul class="navbar-nav ml-auto ">
        <%if user_signed_in?%>
          <li class="nav-item <%= 'active' if current_page?(activities_path) %>"><%= link_to "Activities", activities_path, class: "nav-link" %></li>
        <%else%>
          <li class="nav-item"><%= link_to "Log in", new_user_session_path, class: "nav-link" %></li>
        <%end%>
        <li class="nav-item <%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path, class: "nav-link" %></li>
        <li class="nav-item <%= 'active' if current_page?(contact_path) %>"><%= link_to "Contact", contact_path, class: "nav-link" %></li>
        <%if user_signed_in?%>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, class: "nav-link", :method => :delete do %>
              <%# <span class="iconify" data-icon="ic:twotone-log-out" data-inline="false"></span> %>
              Log out
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>