config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "home#index"
  get 'home/index'

  resources :activity_types
  resources :activities
  
  get 'about', to: "about_contact#about"
  get 'contact', to: "about_contact#contact"
end

app/controllers/activity_types_controller.rb
class ActivityTypesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_is_admin
  before_action :set_activity_type, only: [:show, :edit, :update, :destroy]


  def check_is_admin
    if !current_user.has_role? :admin
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  def index
      @activity_types = ActivityType.all
      
  end

  def show 
  end

  def new 
      @activity_type = ActivityType.new
  end

  def edit
  end


  def create
    @activity_type = ActivityType.new(activity_type_params)
    respond_to do |format|
      if @activity_type.save
        format.html { redirect_to activity_types_url, notice: 'Activity Type was successfully created.' }
        format.json { render :show, status: :created, location: @activity_type }
      else
        format.html { render :new }
        format.json { render json: @activity_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @activity_type.update(activity_type_params)
        format.html { redirect_to activity_types_url, notice: 'Activity Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity_type }
      else
        format.html { render :edit }
        format.json { render json: @activity_type.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @activity_type.destroy
    respond_to do |format|
      format.html { redirect_to activity_types_url, notice: 'Activity Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_activity_type
    @activity_type = ActivityType.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def activity_type_params
    params.fetch(:activity_type, {}).permit(
      :name,
      :calories_factor,
      :image
    )
  end

end

app/helpers/activity_types_helper.rb
module ActivityTypesHelper
end

app/views/activity_types/_form.html.erb
<%= form_with(model: activity_type, local: true, class: "") do |f| %>

  <% if activity_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity_type.errors.count, "error") %> prohibited this activity_type from being saved:</h2>

      <ul>
        <% activity_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Name</label>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <label>Calories factor (calories per minute)</label>
    <%= f.number_field :calories_factor %>
  </div>

  <div class="form-group">
    <label>Image:</label>
    <%= image_tag(activity_type.image_url, class:"svg-image") if activity_type.image? %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit "Save" %>
<% end %>

app/views/activity_types/edit.html.erb
<p>Edit activity type</p>

<%= render partial: "form", locals: {activity_type: @activity_type} %>

app/views/activity_types/index.html.erb
<h1>Activity Types</h1>

<table>
  <thead>
    <tr>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @activity_types.each do |activity_type| %>
      <tr>
        <td><%= activity_type.name %></td>
        <td class="activity-type-img-td"><%= raw activity_type.image.read if activity_type.image? %></td>
        <td><%= link_to 'Show', activity_type %></td>
        <td><%= link_to 'Edit', edit_activity_type_path(activity_type) %></td>
        <td><%= link_to 'Destroy', activity_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity Type', new_activity_type_path %>

app/views/activity_types/new.html.erb
<p>New activity type</p>

<%= render partial: "form", locals: {activity_type: @activity_type} %>