config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "home#index"
  get 'home/index'

  resources :activity_types
  resources :activities
  
  get 'about', to: "about_contact#about"
  get 'contact', to: "about_contact#contact"
end

app/models/activity.rb
class Activity < ApplicationRecord

  belongs_to :activity_type

  belongs_to :user

  validates :start, presence: { message: "Please fill up the activity start time"}
  validates :duration, 
    presence: { message: "Please fill up the activity duration" }, 
    numericality: { 
      only_integer: true, 
      greater_than: 0,
      message: "Activity duration is not a number or is not greater than zero" 
    }
  
end

app/models/activity_type.rb
class ActivityType < ApplicationRecord
    mount_uploader :image, ActivityTypeUploader

    has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  layout "application_content"

  before_action :authenticate_user!

  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  before_action except: [:create, :update, :destroy] do
    @title = "Activities"  
    @background_class = "activity-background"
  end

  # GET /activities
  # GET /activities.json
  def index

    # default show activities starting two months ago
    from_date = Time.now - 2.months
    to_date = Time.now + 2.months

    if(params.has_key?(:start_date))
      from_date = Time.parse(params[:start_date]) - 3.months
      to_date = Time.parse(params[:start_date]) + 3.months
    end

    @activities = Activity.includes(:activity_type).where("user_id=? and start>=? and start<=?", current_user.id, from_date, to_date)

    total_duration = Activity.where("user_id=?", current_user.id).group(:user_id).sum(:duration)[1]
    
    @total_hours = 0
    @total_minutes = 0
    if !total_duration.nil?
      @total_hours = total_duration / 60
      @total_minutes = total_duration % 60
    end

    #total calories
    sql = <<-SQL
      SELECT
        activities.user_id,
        SUM(activities.duration*activity_types.calories_factor) as calories
      FROM activities
      JOIN activity_types ON
        activities.activity_type_id = activity_types.id
      WHERE activities.user_id=#{ActiveRecord::Base.connection.quote(current_user.id)}
      GROUP BY activities.user_id
    SQL
    first = Activity.find_by_sql(sql).first
    @total_calories = first.nil? ? 0 : first.calories

    # favorite activity calculated as activity type with longest duration
    favorite = ActivityType.select('activity_types.id, activity_types.name')
                  .left_joins(:activities)
                  .where("activities.user_id=?", current_user.id)
                  .group('activity_types.id')
                  .sum('activities.duration')

    sql = <<-SQL
      SELECT
        activity_types.id,
        activity_types.name,
        SUM(activities.duration) as duration
      FROM activity_types
      JOIN activities ON
        activities.activity_type_id = activity_types.id
      WHERE activities.user_id=#{ActiveRecord::Base.connection.quote(current_user.id)}
      GROUP BY activity_types.id
      ORDER BY duration DESC
    SQL
    first = ActivityType.find_by_sql(sql).first
    @favorite_activity_type = first.nil? ? "-" : first.name




    # duration per day for last 30 days
    if Rails.env.production?
      sql = <<-SQL
        SELECT
          date_trunc('day', start) "start_date",
          SUM(duration) as duration
        FROM activities
        WHERE user_id=#{ActiveRecord::Base.connection.quote(current_user.id)} 
          AND start<=#{ActiveRecord::Base.connection.quote(Time.now)}
          AND start>=#{ActiveRecord::Base.connection.quote(Time.now - 31.days)}
        GROUP BY 1
      SQL
      data = Activity.find_by_sql(sql).map{ |i| {start: i[:start_date].strftime("%F"), duration: i[:duration]} }
        .each_with_object({}) { |k, h| h[k[:start]] = {:duration => k[:duration] } }
    else
      sql = <<-SQL
        SELECT
          SUM(duration) as duration,
          date(start) as start_date
        FROM activities
        WHERE user_id=#{ActiveRecord::Base.connection.quote(current_user.id)}
          AND start<=#{ActiveRecord::Base.connection.quote(Time.now)}
          AND start>=#{ActiveRecord::Base.connection.quote(Time.now - 31.days)}
      GROUP BY date(start)
      SQL
      data = Activity.find_by_sql(sql).index_by { |t| t.start_date }
    end

    @minutes_data = {}
    (0..30).each { |i|
      i = 30 - i
      day = (Time.now - i.days).to_date
      count = 0
      if !data[day.strftime("%F")].nil?
        count = data[day.strftime("%F")][:duration]
      end
      @minutes_data[day.strftime("%b %d")] = count
    }

    # calories per day for last 30 days
    if Rails.env.production?
      sql = <<-SQL
        SELECT
          date_trunc('day', start) "start_date",
          SUM(activities.duration*activity_types.calories_factor) as calories
        FROM activities
        JOIN activity_types ON
          activities.activity_type_id = activity_types.id
        WHERE user_id=#{ActiveRecord::Base.connection.quote(current_user.id)}
          AND start<=#{ActiveRecord::Base.connection.quote(Time.now)}
          AND start>=#{ActiveRecord::Base.connection.quote(Time.now - 31.days)}
        GROUP BY 1
      SQL
      data = Activity.find_by_sql(sql).map{ |i| {start: i[:start_date].strftime("%F"), calories: i[:calories]} }
        .each_with_object({}) { |k, h| h[k[:start]] = {:calories => k[:calories] } }
    else
      sql = <<-SQL
        SELECT
          SUM(activities.duration*activity_types.calories_factor) as calories,
          date(start) as start_date
        FROM activities
        JOIN activity_types ON
          activities.activity_type_id = activity_types.id
        WHERE activities.user_id=#{ActiveRecord::Base.connection.quote(current_user.id)}
          AND start<=#{ActiveRecord::Base.connection.quote(Time.now)}
          AND start>=#{ActiveRecord::Base.connection.quote(Time.now - 31.days)}
        GROUP BY date(activities.start)
      SQL
      data = Activity.find_by_sql(sql).index_by { |t| t.start_date }
    end

    @calories_data = {}
    (0..30).each { |i|
      i = 30 - i
      day = (Time.now - i.days).to_date
      count = 0
      if !data[day.strftime("%F")].nil?
        count = data[day.strftime("%F")][:calories]
      end
      @calories_data[day.strftime("%b %d")] = count
    }

  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new

    @activity.start = Time.now

  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user

    respond_to do |format|
      if @activity.save
        format.html { redirect_to activities_path, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activities_path, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.fetch(:activity, {}).permit(
        :name,
        :start,
        :duration,
        :activity_type_id
      )
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper

  def show_svg(path)
    File.open(Rails.public_path.to_s + path, "rb") do |file|
      raw file.read
    end
  end

end

app/views/activities/_form.html.erb
<script>
  var startTime = '<%= activity.start.nil? ? 'null' : activity.start.strftime("%FT%T%:z")%>';
  var activityTypes = <%=raw  ActivityType.all.map{|item| {id: item.id, name: item.name, image: show_svg(item.image.url)}}.to_json%>;
  var activityTypeSelected = <%= activity.activity_type_id.nil? ? 'null' : activity.activity_type_id %>;
</script>


<div id='form-app' v-cloak>

  <%= form_with(model: activity, local: true) do |form| %>

    <div class="form-group">
      <label>Please select activity</label>

      <div class="activity-types-list">
        <div v-for="item in activityTypes" class="item" v-bind:class="{ active: item.id == activityTypeSelected }" @click="itemClicked(item)">
          <div v-html="item.image"></div>
          <span>{{item.name}}</span>
        </div>
      </div>
      <input type="hidden" name="activity[activity_type_id]" :value="activityTypeSelected">
      <% if activity.errors[:activity_type].any? %>
        <% activity.errors[:activity_type].each do |message| %>
          <div class="error-note"><%= message %></div>
        <% end %>
      <% end %>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label>Activity start time</label>
          <datetime type="datetime" input-class="form-control" v-model="datetime" hidden-name="activity[start]"></datetime>
          <% if activity.errors[:start].any? %>
            <% activity.errors[:start].each do |message| %>
              <div class="error-note"><%= message %></div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label>Activity duration in minutes</label>
          <%= form.number_field :duration, class: "form-control" %>
          <% if activity.errors[:duration].any? %>
            <% activity.errors[:duration].each do |message| %>
              <div class="error-note"><%= message %></div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>




    <div class="actions text-center">
      <%= form.submit class: 'btn btn-submit' %>
    </div>
  <% end %>


</div>

app/views/activities/edit.html.erb
<section class="content-main">
  <div class="container-fluid status-part">
      <div class="row">
        <div class="col-12">
          <div class="my-breadcrumb">
            <ul>
              <li class="arrow"><i class="fas fa-greater-than"></i></li>
              <li class="text">
                <%= link_to "My activities", activities_path%>
              </li>
              <li class="arrow"><i class="fas fa-greater-than"></i></li>
              <li class="text">Edit Activity</li>
            </ul>
          </div>
        </div>
      </div>

      <div class="row notice-row">
        <div class="col-12">
          <p class="notice"><%= notice %></p>
        </div>
      </div>

  </div>

  <div class="container content-part">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <%= render 'form', activity: @activity %>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/activities/index.html.erb
<section>
  <div class="container-fluid status-part">
      <div class="row">
        <div class="col-6">
          <div class="my-breadcrumb">
            <ul>
              <li class="arrow"><i class="fas fa-greater-than"></i></li>
              <li class="text">My activities</li>
            </ul>
          </div>
        </div>
        <div class="col-6 text-right">
          <%= link_to new_activity_path, class: "btn btn-yellow" do %>
            <i class="fas fa-plus-circle"></i> Add new activity
          <% end %>
        </div>
      </div>

      <div class="row notice-row">
        <div class="col-12">
          <p class="notice"><%= notice %></p>
        </div>
      </div>
  </div>




  <div class="container-fluid content-part">
    <div class="row">

      <div class="col-lg-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Summary</h5>
            <p>Total activities time: <%= @total_hours %> hours <%= @total_minutes %> minutes</p>
            <p>Total calories burned: <%= @total_calories %></p>
            <p>Favorite activity: <%= @favorite_activity_type %></p>

            <div class="chart-title">Duration of activities in minutes per day in the last 30 days</div>
            <%= column_chart @minutes_data, height: "300px", colors: ["rgba(250, 222, 38, 0.6)"] %>

            <div class="chart-title">Calories burned in the last 30 days</div>
            <%= column_chart @calories_data, height: "300px", colors: ["rgba(250, 222, 38, 0.6)"] %>

          </div>
        </div>
      </div>

      <div class="col-lg-8">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Activities calendar</h5>
            <%= month_calendar(attribute: :start, events: @activities) do |date, activities| %>
              <p class="day-label"><%= date.day %></p>

              <% activities.each do |activity| %>
                  <%= link_to activity_path(activity.id), class: "calendar-activity-item" do %>
                    <%= activity.start.strftime("%H:%M") %>
                    <%= activity.activity_type.name %>
                    <%= activity.duration %> min
                  <% end %>
              <% end %>              

            <% end %>
          </div>

        </div>
      </div>

    </div>
  </div>
</section>

app/views/activities/new.html.erb
<section class="content-main">
  <div class="container-fluid status-part">
      <div class="row">
        <div class="col-12">
          <div class="my-breadcrumb">
            <ul>
              <li class="arrow"><i class="fas fa-greater-than"></i></li>
              <li class="text">
                <%= link_to "My activities", activities_path%>
              </li>
              <li class="arrow"><i class="fas fa-greater-than"></i></li>
              <li class="text">New Activity</li>
            </ul>
          </div>
        </div>
      </div>

      <div class="row notice-row">
        <div class="col-12">
          <p class="notice"><%= notice %></p>
        </div>
      </div>

  </div>

  <div class="container content-part">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <%= render 'form', activity: @activity %>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/activities/show.html.erb
<section class="content-main">
  <div class="container-fluid status-part">
      <div class="row">
        <div class="col-12">
          <div class="my-breadcrumb">
            <ul>
              <li class="arrow"><i class="fas fa-greater-than"></i></li>
              <li class="text">
                <%= link_to "My activities", activities_path%>
              </li>
              <li class="arrow"><i class="fas fa-greater-than"></i></li>
              <li class="text"><%= @activity.activity_type.name %>, <%= @activity.start.strftime("%b %e, %H:%M") %></li>
            </ul>
          </div>
        </div>
      </div>

      <div class="row notice-row">
        <div class="col-12">
          <p class="notice"><%= notice %></p>
        </div>
      </div>

  </div>

  <div class="container content-part">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card activity-card">
          <div class="card-body">
            <div class="d-flex justify-content-between">
              <h5 class="card-title">Activity</h5>
              <div>
                <%= link_to edit_activity_path(@activity.id), class: "btn btn-sm btn-blue" do %>
                  <i class="fas fa-pencil-alt"></i>
                <% end %>
                <%= link_to @activity, method: :delete, data: { confirm: 'Do You really want to delete the activity?' }, class: "btn btn-sm btn-alert" do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
              </div>
            </div>
            <div class="text-center">
              <div class="svg-place">
                <%= show_svg(@activity.activity_type.image.url)%>
              </div>
            </div>
            
            <p>Activity type: <span class="property-val"><%= @activity.activity_type.name %></span></p>
            <p>Activity duration: <span class="property-val"><%= @activity.duration %> min</span></p>
            <p>Calories burned: <span class="property-val"><%= @activity.duration * @activity.activity_type.calories_factor %></span></p>
        
          
          
          
          </div>
        </div>
      </div>
    </div>
  </div>
</section>